server:
  port: 6506

spring:
  application:
    name: service-data-elasticsearch
  redis:
    database: 12
    host: 10.0.0.210
    port: 6379
  data:
    elasticsearch:
      repositories:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@10.0.0.210:5901/eureka
    healthcheck:
      enabled: true                             # 开启健康检查（依赖spring-boot-starter-actuator）
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
