server:
  port: 6506

spring:
  application:
    name: service-data-elasticsearch
  redis:
    database: 12
    host: r-wz90c7cf07475764.redis.rds.aliyuncs.com
    port: 6379
    password: ATQ3*vDjmS65Zl8i

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@172.18.0.16:5901/eureka
    healthcheck:
      enabled: true                             # 开启健康检查（依赖spring-boot-starter-actuator）
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000