server:
  port: 6506

spring:
  application:
    name: service-data-elasticsearch
  redis:
    database: 12
    host: r-wz9af2c28c6b9b94.redis.rds.aliyuncs.com
    port: 6379
    password: Ax12RS*yX9T2OK00

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:Bb47C6@172.18.191.175:5901/eureka
    healthcheck:
      enabled: true                             # 开启健康检查（依赖spring-boot-starter-actuator）
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000